### ISSUE TITLE
Need to update license on badge in readme.

### ISSUE THREAD

**Issue by micwoj92** [htcfreek/AutoIT-Scripts#1]
Still says MIT. 

By the way: I assume that these are all separate scripts all in separate folders. Nothing stops you then from having different license per tool and having separate license files per folder.

**Comment by htcfreek** [comment]
This is a bit strange. If I copy badge link and open it directly in browser it shows correctly. Seems to be a GitHub bug. Maybe you know why.

Can be that I improve directory structure this weekend. But here in Germany it is 10.30 p.m. so I will got to bed soon. 😴

**Comment by micwoj92** [comment]
> This is a bit strange. If I copy badge link and open it directly in browser it shows correctly. Seems to be a GitHub bug. Maybe you know why.

GitHub doesn't link directly to that file, if you right click from readme, open in new tab then it takes you to this image address

https://camo.githubusercontent.com/8ddb5f7a464da9f193fe2ebe7e9c583a92f4f90b0e74446db85ff362795537c2/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f687463667265656b2f4175746f49542d53637269707473

 so probably it didn't update in cache yet.


> Can be that I improve directory structure this weekend. But here in Germany it is 10.30 p.m. so I will got to bed soon. sleeping

Yeah, here is 22:43 too, have a good rest!

**Comment by htcfreek** [comment]
@micwoj92 
Fixed. The problem was the difference between `AutoIT-Scripts` (doesn't work) and `autoit-scripts` (works) within the url for the badge.

**Comment by micwoj92** [comment]
Oh that was weird, I thought it was case sensitive.

**Comment by htcfreek** [comment]
Some badges seem to be not.
