### ISSUE TITLE
"GetDiskInfo.au3": there are typos in the word "Partition"

### ISSUE THREAD

**Issue by htcfreek** [htcfreek/AutoIT-Scripts#14]
Describe the bug
In the file "GetDiskInfo.au3" there are typos in the word "Partition".

_Originally posted by @Oleg-Chashko in https://github.com/rcmaehl/WhyNotWin11/issues/386#issuecomment-873478230._

**Comment by htcfreek** [comment]
`$aPrtitionList` in 
https://github.com/htcfreek/AutoIT-Scripts/blob/a3f19456b688a3791f799e8b15d5fbf90ffdcde2/src/GetDiskInfoFromWmi/GetDiskInfoFromWmi.au3#L3

**Comment by Oleg-Chashko** [comment]
P-**a**-rtit-**i**-on in

**Line 3:** Func _GetDiskInfoFromWmi(ByRef $aDiskList, ByRef $aPrtitionList, $bAddTableHeader = 1)
**Line 10:** Input parameter: ByRef $aDiskList = Array var for list of disks.; ByRef $aPrtitionList = Array var for list of partitions.; [$bAddTableHeader = 1] = Should array tables have a header rows.
**Line 65:** $aPartitions[$iPartArrayCount][9] = $oLogicalDisk.Size ; Value of LogicalDisk.Size is different to Size of DiskPartiton.Size!!
**Line 87:** $aPrtitionList =  $aPartitions

**Comment by Oleg-Chashko** [comment]
Di-**s**-ks in

**Line 58:** Get LogicalDiks

**Comment by Oleg-Chashko** [comment]
Env-**G**-et in

**Line 70:** if $oLogicalDisk.DeviceID = Envget("SystemDrive") Then

**Comment by Oleg-Chashko** [comment]
It was a pleasure to help you. :)

**Comment by Oleg-Chashko** [comment]
@htcfreek 

Although this will not affect the work of the code, only the beauty of writing code.
If you write code in the same style, it is desirable to change:

**Line 24:** "DiskInterfacetype" & "||" & "DiskMediatype" & "||" & "DiskSerialnumber"
**Line 40:** " & $oDisk.Interfacetype & "||" & $oDisk.Mediatype & "||" & $oDisk.Serialnumber & "
change to
**Line 24:** "DiskInterface**T**ype" & "||" & "DiskMedia**T**ype" & "||" & "DiskSerial**N**umber"
**Line 40:** " & $oDisk.Interface**T**ype & "||" & $oDisk.Media**T**ype & "||" & $oDisk.Serial**N**umber & "

**Comment by htcfreek** [comment]
Thanks @Oleg-Chashko . I hope everything is fixed now.

**Comment by htcfreek** [comment]
New release is coming soon.

**Comment by htcfreek** [comment]
Released (v1.2).
